"""empty message

Revision ID: 21299df263be
Revises: 2442f9877f5c
Create Date: 2022-08-06 22:42:53.848376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21299df263be'
down_revision = '2442f9877f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('look_for_venue', sa.Boolean(), nullable=False))
    op.drop_column('Artist', 'look_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('look_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Artist', 'look_for_venue')
    # ### end Alembic commands ###
